export const AppRoute = {
  AUTH: "auth",
  SIGN_IN: "sign-in",
  RESET_PASSWORD: "reset-password",
  MAIN: "main",
  RSVP: "rsvp",
  FOOD: "food",
  SCAN: "scan",
  SCHEDULE: "schedule",
  STORY: "our_story",
  QUIZ: "quiz",
  GUEST_CREATE: "add_guest",
  INVITATION: "invitation",
  ADMIN_PANEL: "admin_panel",
  GUEST_LIST: "guest_list",
  ADD_QUIZ: "add_quiz",
  ADD_SCHEDULE: "add_schedule",
  ADD_FOODS: "add_foods",
};
