export const CREATE_FOODS_REQUEST = "mobile/SCHEDULE/CREATE_FOODS_REQUEST";

export const CREATE_FOODS_SUCCESS = "mobile/SCHEDULE/CREATE_FOODS_SUCCESS";

export const CREATE_FOODS_FAILURE = "mobile/SCHEDULE/CREATE_FOODS_FAILURE";
