export const POST_SCHEDULE_REQUEST = "mobile/SCHEDULE/POST_SCHEDULE_REQUEST";

export const POST_SCHEDULE_SUCCESS = "mobile/SCHEDULE/POST_SCHEDULE_SUCCESS";

export const POST_SCHEDULE_FAILURE = "mobile/SCHEDULE/POST_SCHEDULE_FAILURE";
