export const POST_QUIZ_REQUEST = "mobile/QUIZ/POST_QUIZ_REQUEST";

export const POST_QUIZ_SUCCESS = "mobile/QUIZ/POST_QUIZ_SUCCESS";

export const POST_QUIZ_FAILURE = "mobile/QUIZ/POST_QUIZ_FAILURE";
